ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
    additional_dependencies:
    - setuptools>=69.2.0
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes, --indent, "2"]
    additional_dependencies:
    - setuptools>=69.2.0

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v3.1.0"
  hooks:
  - id: prettier
    types_or: [markdown, html, css, scss, javascript, json]
    args: [--prose-wrap=preserve]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: insert-license
    exclude: ^\..*$
    types: [python]
    args: [--comment-style, "|#|", --license-filepath, ./LICENSE_HEADER.txt]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.6.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: name-tests-test
    args: ["--pytest-test-first"]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes", "--preview"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    files: src|tests
    args: [--no-install-types]
    additional_dependencies:
    - dace==0.15.1
    - jax[cpu]==0.4.28
    - numpy==1.26.4
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.10.0.1"
  hooks:
  - id: shellcheck

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
    exclude: .pre-commit-config.yaml

- repo: https://github.com/abravalheri/validate-pyproject
  rev: "v0.16"
  hooks:
  - id: validate-pyproject
    additional_dependencies: ["validate-pyproject-schema-store[all]"]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: "0.28.1"
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
  - id: check-readthedocs
